### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by TriNguyen479** [TriNguyen479/dinosaur-designs#1]
![image](https://user-images.githubusercontent.com/77295941/110363710-e3866580-8010-11eb-9387-7287ef9bb327.png)
@hellachella

**Comment by hellachella** [comment]
Please commit all of your work.

**Comment by TriNguyen479** [comment]
Ok, I just did

**Comment by hellachella** [comment]
You are missing a closing `;` on line 14. The color declaration.

**Comment by TriNguyen479** [comment]
Got it. Thank you

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/110397781-80142c00-8040-11eb-9d53-3132293ca149.png)
Hi. My web page is visually different than the screenshot 15%, but I can't find the differences. 
@hellachella

**Comment by hellachella** [comment]
It fully passes on my end, is it still doing this to you? Are you using windows?

**Comment by TriNguyen479** [comment]
Yeah, it won't let me pass. I'm using window

**Comment by hellachella** [comment]
Manually graded. pls close the issue.

**Comment by TriNguyen479** [comment]
Sweet. Thank you
